/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'addApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addOwner' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'checkApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'listVatRates' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))], []),
  'payVat' : IDL.Func([IDL.Float64, IDL.Nat], [IDL.Float64], []),
  'removeApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'upsertVat' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'addApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addOwner' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'checkApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'listVatRates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
        [],
      ),
    'payVat' : IDL.Func([IDL.Float64, IDL.Nat], [IDL.Float64], []),
    'removeApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'upsertVat' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };